### ISSUE TITLE
Hints jshint

### ISSUE THREAD

**Issue by duard** [tutts/es6-express-mongoose-passport-rest-api#5]
How can I fix this hints in the code 
![screen shot 2017-10-03 at 7 06 14 am](https://user-images.githubusercontent.com/36894/31120079-93db59d8-a809-11e7-9c83-95d6f7628704.png)

**Comment by tutts** [comment]
Hi!

It looks like you have an ESlint plugin built into your IDE, as theres no config it will use the default or traverse until it finds one (I think).

So if you want to use ESlint with Prettier, add ESlint to your project and create a config file for it, you can add the [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) module to your node application, and then use the following extensions:

```javascript
{
  "extends": [
    "prettier",
    "prettier/standard"
  ]
}
```

this should then solve your issue :)

**Comment by tutts** [comment]
Actually thinking about this again, whats the ESLint error you get? It won't be a Prettier compatibility issue, it will be that ESLint doesn't know about [Object spreading](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator), so you'll need to add a rule to either ignore it, or refactor into an [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

**Comment by duard** [comment]
I'm using VSCODE, what is your editor ? If do you use VSCODE what is yours extensions/plugins ?

**Comment by duard** [comment]
When i open my vscode I see that message

**Cannot find module 'eslint-config-prettier/standard' Referenced from: /Users/duard/Development/api-es6/.eslintrc******

**Comment by duard** [comment]
Everything is fine now

https://www.npmjs.com/package/eslint-plugin-prettier
